$(function(){
    $('*').css({
        'margin':'0',
        'padding':'0'
    });
    $('body').css({
        'margin':'0 auto',
        'height':'1319px'
    });
    $('.container').css({
        'width':'auto',
        'height':'auto'
    });
    $('.imgjumbotron').css({
        'width':'100%',
        'height':'695px',
    });
    $('.menu').css({
        'width':'100%',
        'height':'71px',
        'background':'rgba(225,225,225,.5)',
        'marginTop':'-71px',
        'position':'absolute'
    });
    $('.text-container').css({
        'width':'200px',
        'height':'80px',
        'background':'rgba(225,225,225,.5)',
        'position':'absolute',
        'marginLeft':'50px',
        'marginTop':'20px'
    });
    $('.text-container').eq(1).css({
        'marginLeft':'400px',
        'marginTop':'200px'
    });
    $('.text-container').eq(2).css({
        'marginTop':'400px'
    });
    $('.maintext').css({
        'width':'500px',
        'height':'624px',
        'position':'absolute',
        'background':'rgba(0,0,0,0.5)',
        'marginLeft':'850px'
    });
    $('.submaintext').css({
        'width':'400px',
        'height':'60px',
        'background':'rgba(225,225,225,.0)',
        'position':'absolute',
        'fontFamily':'Idealist Sans',
        'color':'white',
        'textAlign':'center',
        'fontSize':'30px',
        'marginLeft':'50px',
        'marginTop':'100px',
        'paddingTop':'10px',
        'borderBottom':'solid 1px white'
    });
    $('.submaintext').eq(1).css({
        'marginTop':'160px',
        'width':'200px',
        'fontSize':'25px',
        'paddingTop':'17px',
        'height':'60px',
        'fontFamily':'timeBurner',
        'borderRight':'solid 1px white',
        'borderBottom':'0',
        'background':'rgba(225,225,225,.0)'
    });
    $('.submaintext').eq(2).css({
        'marginTop':'160px',
        'width':'190px',
        'fontSize':'14px',
        'fontFamily':'timeBurner',
        'paddingTop':'2px',
        'height':'50px',
        'borderRight':'solid 0px white',
        'borderBottom':'0',
        'height':'60px',
        'marginLeft':'250px',
        'textAlign':'left',
        'paddingLeft':'10px',
        'background':'rgba(225,225,225,.0)'
    });
    $('.isitext').css({
        'width':'100px',
        'height':'40px',
        'background':'rgba(0,0,0,0.0)',
        'fontFamily':'timeBurner',
        'borderRight':'solid 1px black',
        'position':'absolute',
        'fontSize':'20px',
        'textAlign':'center',
        'paddingTop':'7px',
        'marginTop':'20px',
        'color':'black'
    });
    $('.isitext2').css({
        'marginLeft':'110px',
        'borderRight':'0',
        'fontFamily':'timeBurner',
        'fontSize':'15px',
        'padding':'0',
        'background':'rgba(0,0,0,0.5)',
        'textAlign':'left',
        'width':'200px',
        'height':'40px',
        'height':'40px',
        'paddingLeft':'10px',
        'marginTop':'20px',
        'color':'white'
    });
    $('.jadwal').css({
        'width':'400px',
        'height':'300px',
        'position':'absolute',
        'background':'rgba(225,225,225,.0)',
        'marginTop':'300px',
        'marginLeft':'50px'
    });
    $('.subjadwal').css({
        'width':'100%',
        'height':'30px',
        'background':'rgba(0,0,0,0.0)',
        'borderBottom':'solid 1px white',
        'textAlign':'center',
        'fontFamily':'arial',
        'paddingTop':'5px',
        'color':'white',
        'fontSize':'20px'
    });
    $('table').css({
        'marginTop':'5px'
    });
    $('td').css({
        'color':'white',
        'fontFamily':'timeBurner',
        'width':'130px',
        'background':'rgba(0,0,0,0.0)',
        'height':'50px',
        'textAlign':'center',
        'borderRight':'solid 1px white',
        'marginTop':'10px'
    });
    $('.end').css({
        'borderRight':'0'
    });
    $('li').css({
        'width':'20px',
        'height':'20px',
        'borderRadius':'50%',
        'background':'rgba(225,225,225,.0)',
        'listStyle':'none',
        'float':'left',
        'marginTop':'550px',
        'marginLeft':'10px',
        'border':'solid 1px white'
    });
    $('li').eq(0).css({
        'marginLeft':'220px'
    });
    $('.gyminastic').css({
        'color':'white',
        'fontFamily':'Idealist Sans',
        'fontSize':'20px',
        'marginLeft':'10px',
        'marginTop':'20px',
        'position':'absolute'
    });
    $('.buttonmn').css({
        'position':'absolute',
        'marginLeft':'900px',
        'marginTop':'20px'
    });
    $('.btnmenu').css({
        'background':'rgba(0,0,0,0.0 )',
        'border':'0',
        'width':'60px',
        'height':'25px',
        'color':'black',
        'fontSize':'18px',
        'fontFamily':'timeBurner',
        'fontWeight':'bold',
        'marginRight':'20px'
    });
    $('.btnmenu').eq(0).mouseenter(function(){
        $('.btnmenu').eq(0).css({
            'color':'white',
            'transition':'all 0.3s'
        });
    });
    $('.btnmenu').eq(0).mouseleave(function(){
        $('.btnmenu').eq(0).css({
            'color':'black'
        });
    });
    $('.btnmenu').eq(1).mouseenter(function(){
        $('.btnmenu').eq(1).css({
            'color':'white',
            'transition':'all 0.3s'
        });
    });
    $('.btnmenu').eq(1).mouseleave(function(){
        $('.btnmenu').eq(1).css({
            'color':'black'
        });
    });
    $('.btnmenu').eq(2).mouseenter(function(){
        $('.btnmenu').eq(2).css({
            'color':'white',
            'transition':'all 0.3s'
        });
    });
    $('.btnmenu').eq(2).mouseleave(function(){
        $('.btnmenu').eq(2).css({
            'color':'black'
        });
    });
    $('.btnmenu').eq(3).mouseenter(function(){
        $('.btnmenu').eq(3).css({
            'color':'white',
            'transition':'all 0.3s'
        });
    });
    $('.btnmenu').eq(3).mouseleave(function(){
        $('.btnmenu').eq(3).css({
            'color':'black'
        });
    });
    $('.btnmenu').eq(4).mouseenter(function(){
        $('.btnmenu').eq(4).css({
            'color':'white',
            'transition':'all 0.3s'
        });
    });
    $('.btnmenu').eq(4).mouseleave(function(){
        $('.btnmenu').eq(4).css({
            'color':'black'
        });
    });
    $('.container2').css({
        'width':'930px',
        'height':'557px',
        'border':'solid 1px #d2d2d2',
        'margin':'0 auto',
        'background':'#FCFDF7',
        'marginTop':'5px'
    });
    $('footer').css({
        'width':'100%',
        'height':'59px',
        'background':'#FCFDF7',
        'borderTop':'solid 1px #d2d2d2',
        'marginTop':'5px'
    });
    $('.container3').css({
       'position':'absolute',
        'width':'200px',
        'height':'150px',
        'border':'solid 1px #d2d2d2',
        'marginTop':'-557px',
        'marginLeft':'1147px',
        'textAlign':'center',
        'background':'#FCFDF7'
    });
    $('.subcontain2').css({
       'position':'absolute',
        'width':'750px',
        'height':'302px',
        'borderTop':'solid 3px #fff',
        'marginTop':'-170px',
        'marginLeft':'90px',
        'textAlign':'center',
        'background':'rgba(225,225,225,.5)'
    });
    $('#subcontainer3').css({
        'fontSize':'30px',
        'fontFamily':'timeBurner',
        'marginTop':'10px',
        'color':'black'
    });
    $('#subcontainer3-1').css({
        'fontSize':'20px',
        'fontFamily':'timeBurner',
        'marginTop':'10px',
        'color':'black'
    });
    $('.btnsosmed').css({
        'width':'30px',
        'height':'30px',
        'background':'white',
        'border':'solid 1px #d2d2d2',
        'marginTop':'15px',
        'float':'right',
        'marginRight':'10px',
        'color':'black',
        'fontSize':'18px',
        'fontFamily':'timeBurner'
    });
    $('.btnsosmed').eq(0).css({
        'marginRight':'200px'
    });
    $('.btnsosmed').eq(0).mouseenter(function(){
        $('.btnsosmed').eq(0).css({
            'transition':'all 0.5s',
            'background':'#1C5E8D',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(0).mouseleave(function(){
        $('.btnsosmed').eq(0).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.btnsosmed').eq(1).mouseenter(function(){
        $('.btnsosmed').eq(1).css({
            'transition':'all 0.5s',
            'background':'#6FC6DC',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(1).mouseleave(function(){
        $('.btnsosmed').eq(1).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.btnsosmed').eq(2).mouseenter(function(){
        $('.btnsosmed').eq(2).css({
            'transition':'all 0.5s',
            'background':'#F6B190',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(2).mouseleave(function(){
        $('.btnsosmed').eq(2).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.btnsosmed').eq(3).mouseenter(function(){
        $('.btnsosmed').eq(3).css({
            'transition':'all 0.5s',
            'background':'#F17442',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(3).mouseleave(function(){
        $('.btnsosmed').eq(3).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.btnsosmed').eq(4).mouseenter(function(){
        $('.btnsosmed').eq(4).css({
            'transition':'all 0.5s',
            'background':'#0287AF',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(4).mouseleave(function(){
        $('.btnsosmed').eq(4).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.btnsosmed').eq(5).mouseenter(function(){
        $('.btnsosmed').eq(5).css({
            'transition':'all 0.5s',
            'background':'#E3413C',
            'color':'white'
        });
    });
    $('.btnsosmed').eq(5).mouseleave(function(){
        $('.btnsosmed').eq(5).css({
            'background':'#fff',
            'color':'black'
        });
    });
    $('.gym').css({
        'fontFamily':'Idealist Sans',
        'fontSize':'20px',
        'position':'absolute',
        'colot':'black',
        'width':'150px',
        'textAlign':'center',
        'height':'40px',
        'marginTop':'8px',
        'paddingTop':'5px',
        'paddingBottom':'2px',
        'borderRight':'solid 1px black',
        'background':'rgba(0,0,0,0.0)'
    });
    $('.ket').css({
        'fontFamily':'Idealist Sans',
        'fontSize':'11px',
        'position':'absolute',
        'colot':'black',
        'width':'auto',
        'textAlign':'left',
        'height':'40px',
        'marginTop':'8px',
        'paddingTop':'10px',
        'paddingBottom':'2px',
        'paddinLeft':'7px',
        'marginLeft':'160px',
        'wordSpacing':'20px',
        'background':'rgba(0,0,0,0.0)'
    });
    $('.desktopmode').css({
        'fontFamily':'Idealist Sans',
        'fontSize':'11px',
        'position':'absolute',
        'colot':'black',
        'width':'auto',
        'textAlign':'left',
        'height':'25px',
        'marginTop':'10px',
        'paddingTop':'10px',
        'paddingBottom':'2px',
        'paddinLeft':'7px',
        'marginLeft':'1200px',
    });
    $('.asatu').css({
        'textDecoration':'none',
        'color':'black'
    });
    $('.asatu').mouseenter(function(){
        $('.asatu').css({
            'textDecoration':'underline'
        });
    });
    $('.asatu').mouseleave(function(){
        $('.asatu').css({
            'textDecoration':'none'
        });
    });
    $('.adua').css({
        'textDecoration':'none',
        'color':'black'
    });
    $('.adua').eq(0).mouseenter(function(){
        $('.adua').eq(0).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(0).mouseleave(function(){
        $('.adua').eq(0).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(1).mouseenter(function(){
        $('.adua').eq(1).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(1).mouseleave(function(){
        $('.adua').eq(1).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(2).mouseenter(function(){
        $('.adua').eq(2).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(2).mouseleave(function(){
        $('.adua').eq(2).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(3).mouseenter(function(){
        $('.adua').eq(3).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(3).mouseleave(function(){
        $('.adua').eq(3).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(4).mouseenter(function(){
        $('.adua').eq(4).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(4).mouseleave(function(){
        $('.adua').eq(4).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(5).mouseenter(function(){
        $('.adua').eq(5).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(5).mouseleave(function(){
        $('.adua').eq(5).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(6).mouseenter(function(){
        $('.adua').eq(6).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(6).mouseleave(function(){
        $('.adua').eq(6).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(7).mouseenter(function(){
        $('.adua').eq(7).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(7).mouseleave(function(){
        $('.adua').eq(7).css({
            'textDecoration':'none'
        });
    });
    $('.adua').eq(8).mouseenter(function(){
        $('.adua').eq(8).css({
            'textDecoration':'underline',
        });
    });
    $('.adua').eq(8).mouseleave(function(){
        $('.adua').eq(8).css({
            'textDecoration':'none'
        });
    });
    $('.atiga').css({
        'textDecoration':'none',
        'color':'white'
    });
    $('.banner').css({
        'width':'900px',
        'height':'400px',
        'border':'solid 0px black',
        'margin':'0 auto',
        'paddingTop':'10px'
    });
    $('.imgbanner').css({
        'width':'900px',
        'height':'400px'
    });
    $('.next').css({
        'position':'absolute',
        'border':'0',
        'background':'rgba(225,225,225,.8)',
        'width':'50px',
        'height':'60px',
        'marginLeft':'840px',
        'color':'black',
        'fontWeight':'bold',
        'fontSize':'40px',
        'fontFamily':'idealist Sans',
        'marginTop':'170px',
        'textAlign':'center',
    });
    $('.prev').css({
        'position':'absolute',
        'border':'0',
        'background':'rgba(225,225,225,.8)',
        'width':'50px',
        'height':'60px',
        'marginLeft':'10px',
        'color':'black',
        'fontWeight':'bold',
        'fontSize':'40px',
        'fontFamily':'idealist Sans',
        'marginTop':'170px',
        'textAlign':'center',
    });
    $('.facility').css({
       'position' :'absolute',
        'width':'230px',
        'height':'66px',
        'border':'solid 0px white',
        'color':'white',
        'fontFamily':'Idealist Sans',
        'fontSize':'50px',
        'marginTop':'-380px',
        'marginLeft':'200px',
        'textAlign':'center',
        'borderRight':'solid 5px white',
        'background':'rgba(225,225,225,.0)'
    });
    $('.ketfac').css({
       'position' :'absolute',
        'width':'300px',
        'height':'66px',
        'border':'solid 0px white',
        'color':'white',
        'fontFamily':'timeBurner',
        'fontSize':'17px',
        'marginTop':'-380px',
        'marginLeft':'435px',
        'paddingLeft':'10px',
        'background':'rgba(225,225,225,.0)'
    });
    $('.readmore').css({
        'position':'absolute',
        'marginTop':'-300px',
        'marginLeft':'360px',
        'border':'0',
        'width':'200px',
        'height':'40px',
        'background':'rgba(225,225,225,.5)',
        'color':'black',
        'fontSize':'20px',
        'fontFamily':'timeBurner',
        'border':'solid 1px #d2d2d2',
        'fontWeight':'bold'
    });
    $('.readmore').mouseenter(function(){
        $('.readmore').css({
            'background':'rgba(0,0,0,0.5)',
            'color':'white',
            'transition':'all 0.3s'
        });
        $('.readmore').mouseleave(function(){
            $('.readmore').css({
                'background':'rgba(225,225,225,.5)',
                'color':'black'
            });
        });
    });
    $('.garis').css({
        'width':'600px',
        'height':'2px',
        'background':'white',
        'position':'absolute',
        'marginTop':'-250px',
        'marginLeft':'175px'
    });
    $('.navigator').css({
        'border':'solid 1px white',
        'borderRadius':'50%',
        'marginTop':'-220px',
        'position':'absolute',
        'background':'rgba(0,0,0,0.5)',
        'marginLeft':'300px'
    });
    $('.navigator').eq(0).css({
        'marginLeft':'360px',
        'width':'20px',
        'height':'20px'
    });
    $('.navigator').eq(1).css({
        'marginLeft':'400px',
        'width':'25px',
        'height':'25px'
    });
    $('.navigator').eq(2).css({
        'marginLeft':'440px',
        'width':'30px',
        'height':'30px'
    });
    $('.navigator').eq(3).css({
        'marginLeft':'480px',
        'width':'25px',
        'height':'25px'
    });
    $('.navigator').eq(4).css({
        'marginLeft':'520px',
        'width':'20px',
        'height':'20px'
    });
    $('.scsatu').css({
        'width':'240px',
        'height':'282px',
        'border':'solid 1px #d2d2d2',
        'marginTop':'10px',
        'marginLeft':'10px',
        'position':'absolute'
    });
    $('.scsatu').eq(1).css({
        'marginLeft':'255px'
    });
    $('.scsatu').eq(2).css({
        'marginLeft':'500px'
    });
    $('.hmember').css({
        'width':'100%',
        'height':'40px',
        'marginTop':'-5px',
        'fontSize':'15px'
    });
    $('.icon').css({
        'width':'50px',
        'height':'40px',
        'background':'#1C5E8D',
        'border':'0'
    });
    $('.icon').eq(1).css({
        'background':'#6FC6DC'
    });
    $('.icon').eq(2).css({
        'background':'#ac0041'
    });
    $('.explain').css({
        'width':'190px',
        'height':'100%',
        'background':'rgba(0,0,0,0.3)',
        'border':'0'
    });
    $('.imgreg').css({
        'width':'100%',
        'height':'240px',
        'position':'absolute',
        'marginLeft':'-119px'
    });
    $('.inimgreg').css({
        'position':'absolute',
        'width':'100%',
        'height':'202px',
        'border':'solid 0px black',
        'background':'rgba(200,150,0,.5)',
        'marginTop':'38px',
        'marginLeft':'0px'
    });
    $('.txtnama').css({
        'border':'0',
        'width':'200px',
        'height':'27px',
        'marginTop':'10px',
        'paddingLeft':'10px',
        'fontSize':'13px',
        'fontFamily':'tahoma'
    });
    $('.btnreg').css({
        'width':'200px',
        'border':'0',
        'marginTop':'10px',
        'height':'28px',
        'fontSize':'15px',
        'fontFamily':'tahoma',
        'background':'#AC0041',
        'color':'white'
    });
    $('.btnreg').mouseenter(function(){
        $('.btnreg').css({
        'background':'#FCFDF7',
        'color':'black',
        'transition':'all 0.5s'
            });
    });
    $('.btnreg').mouseleave(function(){
        $('.btnreg').css({
        'background':'#AC0041',
        'color':'white',
            });
    });
    $('.map').css({
        'position':'absolute',
        'height':'240',
        'marginLeft':'-119px',
        'width':'100%'
    });
    $('#zin').css({
        'position':'absolute',
        'marginTop':'255px',
        'marginLeft':'40px'
    });
    $('#zout').css({
        'marginTop':'255px',
        'marginLeft':'70px',
        'position':'absolute'
    });
    $('#full').css({
        'position':'absolute',
        'marginTop':'255px',
        'marginLeft':'100px'
    });
    $('.psatu').css({
        'width':'100%',
        'height':'48px',
        'background':'#FCFDF7',
        'borderBottom':'solid 1px #d2d2d2',
        'fontSize':'13px',
        'fontStyle':'italic',
        'textAlign':'left',
        'paddingLeft':'10px',
        'paddingTop':'5px'
    });
    $('.psatu').eq(1).css({
        'background':'#FCFDF7',
        'borderBottom':'solid 1px #d2d2d2'
    });
    $('.psatu').eq(2).css({
        'background':'#FCFDF7',
        'borderBottom':'solid 1px #d2d2d2'
    });
    $('.psatu').eq(3).css({
        'background':'#FCFDF7',
        'borderBottom':'solid 1px #d2d2d2'
    });
    $('.psatu').eq(4).css({
        'background':'#FCFDF7',
        'borderBottom':'solid 0px #d2d2d2'
    });
    $('.psatu').eq(0).mouseenter(function(){
        $('.psatu').eq(0).css({
            'background':'#eee',
            'transition':'all 0.3s'
        });
    });
    $('.psatu').eq(0).mouseleave(function(){
        $('.psatu').eq(0).css({
            'background':'#FCFDF7'
        });
    });
    $('.psatu').eq(1).mouseenter(function(){
        $('.psatu').eq(1).css({
            'background':'#eee',
            'transition':'all 0.3s'
        });
    });
    $('.psatu').eq(1).mouseleave(function(){
        $('.psatu').eq(1).css({
            'background':'#FCFDF7'
        });
    });
    $('.psatu').eq(2).mouseenter(function(){
        $('.psatu').eq(2).css({
            'background':'#eee',
            'transition':'all 0.3s'
        });
    });
    $('.psatu').eq(2).mouseleave(function(){
        $('.psatu').eq(2).css({
            'background':'#FCFDF7'
        });
    });
    $('.psatu').eq(3).mouseenter(function(){
        $('.psatu').eq(3).css({
            'background':'#eee',
            'transition':'all 0.3s'
        });
    });
    $('.psatu').eq(3).mouseleave(function(){
        $('.psatu').eq(3).css({
            'background':'#FCFDF7'
        });
    });
    $('.psatu').eq(4).mouseenter(function(){
        $('.psatu').eq(4).css({
            'background':'#eee',
            'transition':'all 0.3s'
        });
    });
    $('.psatu').eq(4).mouseleave(function(){
        $('.psatu').eq(4).css({
            'background':'#FCFDF7'
        });
    });
    $('.call').css({
        'marginTop':'20px',
        'fontFamily':'timeBurner'
    });
});

window.setTimeout("waktu()",1000);
function waktu(){
    var a ="Senin";
    var b ="Selasa";
    var c ="Rabu";
    var d ="Kamis";
    var e ="Jumat";
    var f ="Sabtu";
    var g ="Minggu";
    var jam = new Date();
    var sekarang = jam.getDay();
    setTimeout("waktu()",1000);
document.getElementById('subcontainer3').innerHTML = jam.getHours()+" : "+jam.getMinutes()+" : "+jam.getSeconds(); 
   var hari = document.getElementById('subcontainer3-1');
    if ( sekarang == 1){
       hari.innerHTML = a +" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else if( sekarang == 2 ){
       hari.innerHTML = b+" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else if( sekarang == 3 ){
       hari.innerHTML = c+" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else if( sekarang == 4 ){
       hari.innerHTML = d+" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else if( sekarang == 5 ){
       hari.innerHTML = e +" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else if( sekarang == 6 ){
       hari.innerHTML = f+" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }else{
       hari.innerHTML = g+" "+jam.getDate()+" "+jam.getMonth()+" "+jam.getFullYear();
   }
}
